extends Node

const VALUE_SPRITES: Dictionary = {
    # Spades
    [0, 0]: preload("res://img/values/2s.tres"),
    [1, 0]: preload("res://img/values/3s.tres"),
    [2, 0]: preload("res://img/values/4s.tres"),
    [3, 0]: preload("res://img/values/5s.tres"),
    [4, 0]: preload("res://img/values/6s.tres"),
    [5, 0]: preload("res://img/values/7s.tres"),
    [6, 0]: preload("res://img/values/8s.tres"),
    [7, 0]: preload("res://img/values/9s.tres"),
    [8, 0]: preload("res://img/values/10s.tres"),
    [9, 0]: preload("res://img/values/js.tres"),
    [10, 0]: preload("res://img/values/qs.tres"),
    [11, 0]: preload("res://img/values/ks.tres"),
    [12, 0]: preload("res://img/values/as.tres"),
    # Hearts
    [0, 1]: preload("res://img/values/2h.tres"),
    [1, 1]: preload("res://img/values/3h.tres"),
    [2, 1]: preload("res://img/values/4h.tres"),
    [3, 1]: preload("res://img/values/5h.tres"),
    [4, 1]: preload("res://img/values/6h.tres"),
    [5, 1]: preload("res://img/values/7h.tres"),
    [6, 1]: preload("res://img/values/8h.tres"),
    [7, 1]: preload("res://img/values/9h.tres"),
    [8, 1]: preload("res://img/values/10h.tres"),
    [9, 1]: preload("res://img/values/jh.tres"),
    [10, 1]: preload("res://img/values/qh.tres"),
    [11, 1]: preload("res://img/values/kh.tres"),
    [12, 1]: preload("res://img/values/ah.tres"),
    # Clubs
    [0, 2]: preload("res://img/values/2c.tres"),
    [1, 2]: preload("res://img/values/3c.tres"),
    [2, 2]: preload("res://img/values/4c.tres"),
    [3, 2]: preload("res://img/values/5c.tres"),
    [4, 2]: preload("res://img/values/6c.tres"),
    [5, 2]: preload("res://img/values/7c.tres"),
    [6, 2]: preload("res://img/values/8c.tres"),
    [7, 2]: preload("res://img/values/9c.tres"),
    [8, 2]: preload("res://img/values/10c.tres"),
    [9, 2]: preload("res://img/values/jc.tres"),
    [10, 2]: preload("res://img/values/qc.tres"),
    [11, 2]: preload("res://img/values/kc.tres"),
    [12, 2]: preload("res://img/values/ac.tres"),
    # Diamonds
    [0, 3]: preload("res://img/values/2d.tres"),
    [1, 3]: preload("res://img/values/3d.tres"),
    [2, 3]: preload("res://img/values/4d.tres"),
    [3, 3]: preload("res://img/values/5d.tres"),
    [4, 3]: preload("res://img/values/6d.tres"),
    [5, 3]: preload("res://img/values/7d.tres"),
    [6, 3]: preload("res://img/values/8d.tres"),
    [7, 3]: preload("res://img/values/9d.tres"),
    [8, 3]: preload("res://img/values/10d.tres"),
    [9, 3]: preload("res://img/values/jd.tres"),
    [10, 3]: preload("res://img/values/qd.tres"),
    [11, 3]: preload("res://img/values/kd.tres"),
    [12, 3]: preload("res://img/values/ad.tres"),
}
